version: 0.2
env:
  variables:
    ECR_REPO_NAME: ecr-demo-app
phases:
  pre_build:
    commands:
      # ECR Public Gallery login
      - aws ecr-public get-login-password --region us-east-1 | docker login -u AWS --password-stdin public.ecr.aws
      
      # ECR login
      - ECR_MAIN_URI="715841364973.dkr.ecr.us-east-1.amazonaws.com"
      - aws ecr get-login-password --region us-east-1 | docker login -u AWS --password-stdin ${ECR_MAIN_URI}

      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}"
  build:
    commands:
      - docker build -t ecr-demo-app:latest .
  post_build:
    commands:
      - docker tag ecr-demo-app:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}

      # Generate image definitions file for ECS
      - printf '[{"name":"demo-app-container","imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json
